services:

  traefik:
    restart: always
    image: "traefik:v2.9"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/traefik_secure.toml:/traefik_secure.toml
      - ./traefik/acme.json:/acme.json


networks:
  web:
    external: true
